### ISSUE TITLE
Allow use keytab to authenticate against OpenShift if Kerberos auth is enabled

### ISSUE THREAD

**Issue by pbabinca** [projectatomic/osbs-client#127]
I want to use osbs as a library for a script which will authenticate against OpenShift using Kerberos. As this isn't regular user the script may (or may not) have valid ticket. There will be keytab issued for osbs service which can be used to create a ticket. I expect osbs to have a configuration to specify absolute path to this keytab file.

**Comment by TomasTomecek** [comment]
I would be in favor of putting this to separate subpackage since we'll need some kerberos lib to do this.
