### ISSUE TITLE
merge all prod build types together

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/osbs-client#129]
They all do very similar thing: let's adapt the workflow according to provided configuration:

* [x] if yum repo is specified, don't use koji plugin
* [x] pulp
 * [x] if admin and password are not specified, ensure secrets is on
 * [ ] if squashing is on, don't load squashed image to engine
* [x] if secret is specified, use k8s secrets

**Comment by twaugh** [comment]
[ ] if no NFS server path is specified, don't use `cp_built_image_to_nfs` plugin

**Comment by mmilata** [comment]
I wonder if we should get rid of *simple* build type as well? It was supposed to do less things than prod builds, however most of the things are now optional.

**Comment by twaugh** [comment]
Agreed.
