### ISSUE TITLE
improve deployment guide

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/osbs-client#157]
Answer @maxamillion questions from rel-eng of fedora:

 - [x] Does OSBS need a Project inside of OpenShift?
 - [x] What kind of access to OpenShift does the OSBS builder need?
 - [x] Can OSBS share an OpenShift environment with other projects/users?
 - [x] document setup with htpasswd and username/password
 - [x] How to configure the above

**Comment by maxamillion** [comment]
Thank you! :)
