### ISSUE TITLE
Better reporting of OpenShift HTTP errors

### ISSUE THREAD

**Issue by mmilata** [projectatomic/osbs-client#167]
Openshift usually returns helpful message in the body of HTTP response when a request resuls in an error. Example for a missing item in Build json:
```
{
  "kind": "Status",
  "apiVersion": "v1beta3",
  "metadata": {},
  "status": "Failure",
  "message": "resource: required value",
  "code": 500
}
```

Reference: https://docs.openshift.org/latest/rest_api/openshift_v1.html#v1-status

We currently ignore the http response body. Printing some of this information might help debugging stuff like #164.

**Comment by TomasTomecek** [comment]
Hmmm, didn't we merge something related to this recently?
