### ISSUE TITLE
Needs delete_buildconfig() API

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#183]
When we create BuildConfigs, an Atomic Reactor plugin will want to be able to delete them on failure (https://github.com/projectatomic/atomic-reactor/pull/230). To do that, it will need an additional API method, `delete_buildconfig()`.

CC @bkabrda

**Comment by bkabrda** [comment]
Yeah, I'll add a commit for that to #181.

**Comment by twaugh** [comment]
This isn't needed now.
