### ISSUE TITLE
Wrong error message if connection is closed in lower layer than application one

### ISSUE THREAD

**Issue by pbabinca** [projectatomic/osbs-client#187]
When I receive streamed logs from OpenShift with `get_build_logs(follow=True)` the connection to OpenShift is sometimes closed due https://github.com/openshift/origin/issues/2348. This is done on lower levels of networking stack than application one.

osbs-client doesn't check this and if `pycurl.error` exception occur it just prints last message `(18, 'NSS: client certificate not found (nickname not specified)')` which isn't error just a warning.

**Comment by TomasTomecek** [comment]
So, what do you propose then? Am not sure I follow precisely.

**Comment by pbabinca** [comment]
Try to query pycurl what was the cause of the lost connection and if it isn't on application level don't print that message.

**Comment by mmilata** [comment]
The error code `18` is `CURLE_PARTIAL_FILE` which corresponds to the message *Transferred a partial file*, which is what happened here. The error message displayed doesn't correspond to the code, which suggests this might be pycurl bug.

Unfortunately pycurl doesn't provide means of translating the code to the human readable string. Looking further into this ...
