### ISSUE TITLE
API for creating an ImageStream

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#190]
See https://github.com/projectatomic/atomic-reactor/issues/248, which depends on this.

The `import_image` plugin needs to be able to create an ImageStream if it does not already exist. There are several options:

 * `get_image_stream()` and `create_image_stream()`
 * `create_image_stream()` only, which raises an exception if it already exists
 * `create_or_update_image_stream()`

**Comment by bkabrda** [comment]
Ok, I guess that means one more commit for https://github.com/projectatomic/osbs-client/pull/181
