### ISSUE TITLE
Basic-auth doesn't work

### ISSUE THREAD

**Issue by bkabrda** [projectatomic/osbs-client#196]
When running osbs-client API functions from atomic-reactor plugins, I'm getting tracebacks like the one that @twaugh posted at https://github.com/projectatomic/osbs-client/pull/195#issuecomment-128051568
It seems that the problem is that osbs-client doesn't send proper `X-CSRF-Token`. For example:
```
# osbs is instance of osbs.api.OSBS
>>> r = osbs.os._get('https://192.168.122.121:8443/oauth/authorize?response_type=token&client_id=openshift-challenging-client', with_auth=False, allow_redirects=False)
>>> r.headers
{'date': 'Thu, 06 Aug 2015 08:18:04 GMT', 'content-length': '77', 'warning': '199 OpenShift "A non-empty X-CSRF-Token header is required to receive basic-auth challenges"', 'content-type': 'text/plain; charset=utf-8'}
```

The `_get` call reproduces what osbs-client does at https://github.com/projectatomic/osbs-client/blob/master/osbs/core.py#L110

**Comment by bkabrda** [comment]
One more note: the configuration used as input for `OSBS` constructor must specify `use_auth=True` for this to occur. Something like:

```
>>> oc = osbs.conf.Configuration(conf_file=None, openshift_uri="https://192.168.122.121:8443", use_auth=True, verify_ssl=False)
>>> osbs=osbs.api.OSBS(oc, oc)
```

**Comment by twaugh** [comment]
See analysis in https://github.com/projectatomic/osbs-client/pull/195#issuecomment-128323654.

**Comment by twaugh** [comment]
@TomasTomecek mentioned that service accounts might be the right approach for plugins to authenticate.
