### ISSUE TITLE
osbs-client should clean up downloaded repositories

### ISSUE THREAD

**Issue by bkabrda** [projectatomic/osbs-client#200]
As it is right now, the code that checks out downloaded repositories (in `osbs/util.py`) doesn't explicitly clean up the repository. This is not a problem if osbs-client is invoked in a one-shot call (since the tmpdir gets removed by Python interpreter when it shuts down), but may become a problem in a long-lived process. Assuming a long-lived process would repeatedly use osbs-client, the number of repositories checked out in tmpdir would just grow until consuming all space.
The only thing we really the repository for is creating a `DockerfileParser` from `Dockerfile` inside the repo and then we can throw it away. So I think the best solution would be for `DockerfileParser` to cache the `Dockerfile` content when instantiated. This way, we could download the repo, create `DockerfileParser` instance and then remove the repo, leaving no unused/unmanaged files in tmpdir.
I'll open an issue for caching support at https://github.com/DBuildService/dockerfile-parse and when that's done, I'll implement the bits in osbs-client.

**Comment by twaugh** [comment]
As it stands right now, the plugin for bumping the Release label will re-use that existing checkout. If we remove it prior to running plugins, we'll need to change that as well.

**Comment by jpopelka** [comment]
There's https://pypi.python.org/pypi/dockerfile-parse/0.0.4 which supports this.
