### ISSUE TITLE
BuildConfigs with triggers don't need to be instantiated?

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#205]
I'm pretty sure that when a BuildConfig is created with triggers, a Build is automatically instantiated. We should probably have a check for that so we don't end up with two builds when we want one, for the first build submission for a component.

CC @bkabrda

**Comment by bkabrda** [comment]
Any reference to a documentation that says this? I haven't been able to find any indication that this is so (and didn't try actually try yet).

**Comment by twaugh** [comment]
I couldn't see any but maybe @csrwng knows where that's documented.

**Comment by bkabrda** [comment]
Hmm, I can't reproduce this behaviour. When I create a BuildConfig throught the API, there's no build instantiated implicitly (or I'm doing something wrong :))

**Comment by csrwng** [comment]
A build will be kicked off if there is an ImageChangeTrigger on the BuildConfig and the "From:" of the image trigger or the BuildConfig itself is of type ImageStreamTag

**Comment by csrwng** [comment]
Looking at the doc, it's not clear that this is what is going to happen, so that needs to be updated.
https://docs.openshift.org/latest/dev_guide/builds.html#build-triggers

**Comment by bkabrda** [comment]
Ok, that makes it clearer and I can reproduce it now. I'll take care of this bug.
