### ISSUE TITLE
Search for Build by label

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#206]
At https://github.com/projectatomic/osbs-client/blob/master/osbs/api.py#L142:

```
        # check if a build already exists for this config; if so then raise
        # TODO: could we do this more effectively than traversing all?
```

Yes, there is a better way: you can search for objects by label. Builds have a `buildconfig` label, naming the BuildConfig they were instantiated from.

CC @bkabrda

**Comment by bkabrda** [comment]
Ah, good point. I'll implement this when I get some free time. The current way works, so I guess there's no rush to do this.

**Comment by bkabrda** [comment]
Note: this is covered by https://github.com/projectatomic/osbs-client/pull/211, so this issue can be closed after that PR is merged.
