### ISSUE TITLE
BuildConfig instantiation polling not quite right

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#216]
For BuildConfigs we expect to instantiate builds automatically we're currently waiting up to 60 seconds for *running* builds, but we have no guarantee the builds will get scheduled in that time. All we need to wait for is *a* build to show up.

Additionally, we shouldn't really need to poll for this, just `watch` (like `OpenShift.wait()` does).

(Aside: I've been trying tests with a trigger listed in the JSON, and trying to work out how to automate tests for this.)

**Comment by bkabrda** [comment]
The current code is waiting for *running* or *pending*. Is that not enough?
Either way, having a way to watch for that build would be nice. I'll try to investigate if that is possible (hopefully sometime next week).

**Comment by twaugh** [comment]
Oh, I was confused by the method name, `_get_running_builds_for_build_config`. I see now, it looks for pending builds as well.

**Comment by bkabrda** [comment]
Yeah, it might be better to use `unfinished` instead of `running` for the method name.

**Comment by TomasTomecek** [comment]
AFAIK with `watch` API call it should be totally doable.
