### ISSUE TITLE
Updating BuildConfig does not remove e.g. secrets

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#244]
When updating an existing BuildConfig, if the existing build JSON described a secret for pulp to use and the new build JSON does not, the secret remains in the BuildConfig after it is updated.

Shouldn't it be removed?

Slightly related to #241, discovered during investigation.

(@bkabrda)

**Comment by bkabrda** [comment]
Yes, it should. This is caused by the way the `utils.deep_update` function works. I'll fix it.
