### ISSUE TITLE
Allow default (None) values for git_branch and git_push_url

### ISSUE THREAD

**Issue by pbabinca** [projectatomic/osbs-client#245]
`git_branch` and `git_push_url` arguments of `create_build()` won't be set to some default value when it would be ignored. I believe `None` should be valid value for both method arguments. Currently code raises an exception:
```
  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 33, in catch_exceptions
    return func(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 338, in create_build
    return self.create_prod_build(namespace=namespace, **kwargs)
  File "/usr/lib/python2.6/site-packages/osbs/api.py", line 44, in catch_exceptions
    raise OsbsException(cause=ex, traceback=sys.exc_info()[2])
OsbsException: TypeError(\'execv() arg 2 must contain only strings\',)
```
If it is called like this ([pseudo code](https://twitter.com/jpavley/status/482637940925792256)):

```
from osbs.api import OSBS
from osbs.conf import Configuration
os_conf = Configuration()
build_conf = Configuration()
osbs = OSBS(os_conf, build_conf)
build_response = osbs.create_build(…
    git_branch=None,
    git_push_url=None
)
```

**Comment by TomasTomecek** [comment]
In current codebase, `None` means default -- not set. We are hitting python limits here.

We could create a constant and set all defaults of api call arguments to it: `DEFAULT_VALUE=0x1337`:
```python
def api_call(self, arg=DEFAULT_VALUE):
    if arg is DEFAULT_VALUE:
        # not set
    else:
        # set
```

**Comment by bkabrda** [comment]
@TomasTomecek I think that this issue is simpler. We either have to make `create_prod_build` explicitly raise if `git_branch` and/or `git_push_url` is `None` (thus disallowing such calls explicitly) or we should set some sensible defaults as a first thing in `create_prod_build`.
IMO it's just a question of checking input params.

**Comment by TomasTomecek** [comment]
If a `create_prod_build` request without `git_branch` and `git_push_url` doesn't make sense at all, I agree. If we should be capable of doing such request, I think we should be able to do both requests: with and without. As I'm looking at the code, it looks like those args are used for bump release plugin. I can imagine workflows where the plugin is not required.

**Comment by bkabrda** [comment]
My point is that in our case we should treat "unspecified value" as "use sane defaults". IMO we can do this without sacrificing anything.

**Comment by TomasTomecek** [comment]
I'll talk to you in person :)

**Comment by twaugh** [comment]
For these two parameters I think we don't even need default sane values. We can just disable all the rebuild triggers if either is None.

**Comment by TomasTomecek** [comment]
Sounds good.
