### ISSUE TITLE
Implement builds/pods deletion from client

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/osbs-client#27]
cleaner.py is a simple script for reaping build containers and pods

merge the functionality into osbs client and run it as cron job

**Comment by TomasTomecek** [comment]
It doesn't make sense to work on this because of these two issues: https://github.com/openshift/origin/issues/1879 https://github.com/openshift/origin/issues/1859

**Comment by TomasTomecek** [comment]
Update: openshift (k8s) reaps containers itself, no need to take care of that. On the other hand, client should be able to remove builds and pods. Ideally in bulk: e.g. *remove all builds older than X*

**Comment by twaugh** [comment]
This will still be needed after we switch to creating BuildConfigs rather than Builds.

**Comment by twaugh** [comment]
This isn't needed after all.
