### ISSUE TITLE
add debug option: mount sources from host

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/osbs-client#29]
...so one can easily debug builds by changing sources on host and not rebuilding the build image:

snippet

```
    # on osbs (builder)
    $ git clone https://github.com/DBuildService/dock.git /mnt/dock
    docker create -v /mnt/dock/dock:/usr/lib/python2.7/site-packages/dock --name dock_sources $image

    # osbs sources
    $ git diff
    diff --git a/osbs/build.py b/osbs/build.py
    index 163d03c..b2d8e66 100644
    --- a/osbs/build.py
    +++ b/osbs/build.py
    @@ -209,6 +209,13 @@ class SimpleBuild(BuildRequest):
             dj.dock_json_set_arg('postbuild_plugins', "store_metadata_in_osv3", "url", self.param['openshift_uri'])


    +@register_build_class
    +class DevBuild(ProductionBuild):
    +    """
    +    """
    +
    +    key = "dev"
    +
     class BuildResponse(object):
         def __init__(self, request):
             """

    $ cat inputs/dev.json
    {
          "metadata":{
            "name": "{{NAME}}"
          },
          "kind": "Build",
          "apiVersion": "v1beta1",
          "parameters": {
            "source" : {
              "type" : "Git",
              "git" : {
                "uri": "{{GIT_URI}}"
              }
            },
            "strategy": {
              "type": "Custom",
              "customStrategy": {
                "image": "buildroot",
                "exposeDockerSocket": true,
                "env": [{
                  "name": "DOCK_PLUGINS",
                  "value": "TBD"
                }],
                "volumeMounts": [{
                    "mountPath": "/usr/lib/python2.7/site-packages/dock",
                    "name": "dock_sources",
                    "readOnly": true
                }]
              }
            },
            "output": {
              "imageTag": "{{OUTPUT_IMAGE_TAG}}",
              "registry": "{{REGISTRY_URI}}"
            }
          }
    }
    $ ls -l inputs/dev_inner.json
    lrwxrwxrwx. 1 me me 15 Apr  9 17:15 inputs/dev_inner.json -> prod_inner.json
```

thanks @pbabinca

**Comment by twaugh** [comment]
Looking at this now.

So, it would also be useful to extend this to [host paths](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/volumes.md) -- `hostDir` / `hostPath` (old name, new name, I think).

I'm trying to work out how the JSON should look in that case but finding it hard to discover the right documentation.

Where is the content of `strategy` documented?

**Comment by TomasTomecek** [comment]
@csrwng could you please help us here? 

We would like to mount arbitrary paths from host to build container and we struggle with finding right docs for the build json.

**Comment by csrwng** [comment]
@TomasTomecek we currently don't give you a way to specify volume mounts in a build definition. One way to get around this is to run a container from your custom builder container that will mount whatever local directory you like and do the build.

**Comment by TomasTomecek** [comment]
Hm, really? I know that @pbabinca managed to do the mounting, see my first comment. Am I missing something?

**Comment by twaugh** [comment]
@TomasTomecek Are kubernetes secret volumes what we actually need for certificates and keys?

**Comment by csrwng** [comment]
@TomasTomecek we don't have a volume mounts struct in the custom strategy: https://github.com/openshift/origin/blob/master/pkg/build/api/v1beta3/types.go#L198-L215. It won't fail if you have that in there, but it won't do anything.

**Comment by csrwng** [comment]
I was chatting with @twaugh and it seems like what you need is to setup a secret if all you need is the pulp certificate/key pair

**Comment by twaugh** [comment]
Secrets can now be mounted for build pods.
