### ISSUE TITLE
Waits for automatic build when no image created

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#305]
Origin won't create a build for a buildconfig if the imagestream it is triggered by doesn't exist, and the image is created inside the build.

As a result, the first build will time out waiting for an automated build that will never happen.

**Comment by TomasTomecek** [comment]
Shouldn't we open against origin?

**Comment by twaugh** [comment]
It seems to me it would be pretty easy to create the image stream from the osbs-client side before the build config is submitted.

That way builds would (I think) be triggered correctly the first time, and the buildroot container would not need to have the `image_stream.json` template installed, which does with the current master branches of osbs-client and atomic-reactor.

**Comment by TomasTomecek** [comment]
Seems like a good solution.

**Comment by twaugh** [comment]
I'm not sure exactly what's wrong, but actually the image created as part of the build is (obviously) a *different* image from the trigger -- so maybe that logic is fine.

Either way, something is up with Build polling when starting from only an ImageStream in Origin.

**Comment by twaugh** [comment]
This issue is not valid. It muddles up the *trigger* ImageStream (the one OpenShift will watch to trigger our build) with the *target* ImageStream (the one we'll create/update in the `import_image` plugin).

Our *trigger* ImageStream will always exist. It's either from a previous layered image build (which we are then building on with `FROM ...`), or it's from a base layer.

If it's from a layered image build, the `import_image` plugin will have created the ImageStream. If not, the build failed and we'll have nothing to `docker pull`.

If it's from a base layer, it is a configuration error for it not to have an ImageStream explicitly created as part of its import procedure.
