### ISSUE TITLE
ImageStream URL is first listed registry URI, should be source_registry_uri

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#308]
When configuring the `import_image` plugin to create an ImageStream, it is told to fetch tags from the (first listed) registry URI.

In fact I think we want this to be the source registry URI. When using pulp, for instance, we want to fetch the repository tags back via crane and use that to trigger builds.

More specifically, I think it should be: the source registry URI, or if that is not set then it should be the first listed registry URI.

**Comment by twaugh** [comment]
More than that, it's actually configuring the wrong URL.

For `import_image`, we need the docker URL to be used, i.e. without the scheme part.

**Comment by twaugh** [comment]
Fixed via #304.

**Comment by lcarva** [comment]
I'm re-implementing this in atomic-reactor to make it work with arrangement 6 and I'm wondering if we ever want to use something other than source registry?

Relevant commit https://github.com/projectatomic/osbs-client/commit/2d613a93a5828e17c5eb8d2ef42ba04a9b70ca78

**Comment by twaugh** [comment]
I think we always want to use the source registry.
