### ISSUE TITLE
refactoring: namespace as a property of OSBS instance

### ISSUE THREAD

**Issue by mmilata** [projectatomic/osbs-client#333]
Currently a lot of methods of `class OSBS` and `class OpenShift` take optional parameter `namespace`. I propose to make it property of those classes and initialize it once in constructor so we don't have to pass it around everywhere.

It's part of our python API but koji-containerbuild doesn't use it. Is it worthwhile?

**Comment by twaugh** [comment]
Seems like a good idea to me, even though it's a API break. Clients can already configure the namespace in osbs.conf, so that should be definitive.
