### ISSUE TITLE
configure tag_and_push plugin with registry secret path

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#335]
Once https://github.com/projectatomic/atomic-reactor/issues/404 is implemented, we'll need to have a new optional configuration parameter `push_secret`, being the name of a Kubernetes secret that contains keys `username`, `email`, and `password` for logging into a registry for pushing.

If this parameter is set, the `tag_and_push` plugin should be configured with `registry_secret_path` being the path to that secret.

**Comment by twaugh** [comment]
@maxamillion

**Comment by TomasTomecek** [comment]
I'm assuming this will also implement pushing to docker hub.

**Comment by twaugh** [comment]
I think that's right.

**Comment by twaugh** [comment]
This is already fixed (e.g. commit 194627a5).
