### ISSUE TITLE
pause_builds(): should it wait for pending builds?

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#348]
When waiting for the resource quota to be satisfied, what happens to a pending build? Has it been admitted, and will inevitably become 'running'?

**Comment by TomasTomecek** [comment]
it should at some point, right? if not, there's a bug in scheduling

**Comment by twaugh** [comment]
Currently `pause_builds()` only checks for builds that are 'running', before returning.

But to be sure all the admitted builds have drained, should it also check for builds that are 'pending'?

i.e. can/does this happen?
1. build submitted (new)
2. new -> pending
3. pods hard quota limit set to 0
4. pending -> running

**Comment by TomasTomecek** [comment]
oh, I misread the question; I guess this would be an excellent question for openshift devs :)

**Comment by twaugh** [comment]
https://github.com/openshift/origin/blob/master/pkg/build/doc.go seems to have the answer:

> For pending builds, the BuildController will attempt to create a pod to perform
the build.

So we should *not* wait for pending builds.

**Comment by twaugh** [comment]
Oh, and now this seems to contradict it:
https://github.com/openshift/origin/blob/master/pkg/build/controller/controller.go#L79

> // HandleBuild deletes pods for cancelled builds and takes new builds and puts
// them in the pending state after creating a corresponding pod

**Comment by nhr** [comment]
Pinging @bparees or @mfojtik; I think this question falls under the DevExp realm.

**Comment by bparees** [comment]
pending builds will sit in pending until sufficient resources are available at which point they will run.

**Comment by twaugh** [comment]
@bparees so when a build is pending, it hasn't created a pod yet? So after setting pod limit to 0, pending builds will stay pending?

**Comment by bparees** [comment]
@twaugh at that point the pod is created, but not scheduled.  so yes, pod limit of zero should leave the build in pending, unless it gets rejected from being created at all based on that limit.

**Comment by twaugh** [comment]
Thanks!
