### ISSUE TITLE
Git reset --hard 'commit' is wrong

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/osbs-client#388]
We should use 'git reset --hard && git checkout <commit>' in ```utils.py``` as I see a lot of 
```
OsbsException(u"Command [u'git', u'reset', u'--hard', u'master'] returned 128\n\nfatal: ambiguous argument 'master': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\n",)
```

**Comment by mmilata** [comment]
Is this on RHEL6? I can't reproduce this and according to man page this usage should be legal (and the one suggested by the error message not legal).

**Comment by vrutkovs** [comment]
No, I've been hitting this on both fedora- and rhel7-based images (not sure why, maybe an old git has been pulled in? Temp repo has been corrupted in between?)
