### ISSUE TITLE
Name label taken exclusively from Dockerfile, 'labels' parameter ignored

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#437]
In `create_prod_build()`:

```
        name_label_name = 'Name'
        try:
            name_label = df_parser.labels[name_label_name]
        except KeyError:
            raise OsbsValidationException("required label '{name}' missing "
                                          "from Dockerfile"
                                          .format(name=name_label_name))
```

but the labels parameter to the method, intended to override Dockerfile labels, is ignored.

@lcarva

**Comment by lcarva** [comment]
There may be other instances in the plugins that do this. Should we remove the generic `label` parameter support and only use instead `release` ? Or should we comb through the code for instances of `df_parser.labels` and change them to read labels from config?

We could also write the given labels into the Dockerfile early enough to avoid this problem altogether.

**Comment by twaugh** [comment]
Now that we know the answer, is this issue still relevant?

**Comment by lcarva** [comment]
Probably not. We also removed the `labels` parameter, so this issue can probably be closed altogether.
