### ISSUE TITLE
osbs option to be deprecated

### ISSUE THREAD

**Issue by rcerven** [projectatomic/osbs-client#476]
osbs option '-c' for component name might be deprecated, as this value is anyway overwritten with value from Dockerfile (BZComponent), unless we want to allow not to specify Component name in Dockerfile and rely in that case on this option

**Comment by twaugh** [comment]
Related: https://github.com/projectatomic/atomic-reactor/issues/580

**Comment by vrutkovs** [comment]
I think it would make sense to make it optional for a start

**Comment by rcerven** [comment]
if this value is really overwritten by component in Dockerfile, that isn't how it was intended (I guess), so if it has to override Component value in Dockerfile it should be optional, but also you should keep in mind the case when it won't be specified and also won't be find in the Dockerfile
