### ISSUE TITLE
scratch builds should have a short random string added to the end of the build name

### ISSUE THREAD

**Issue by vrutkovs** [projectatomic/osbs-client#483]
If several scratch builds are started some might fail if those are submitted to OSE too fast - within one second. 

osbs-client should add a short random string to the build name to ensure this doesn't happen.

**Comment by lcarva** [comment]
the random string should actually be part of the tag as well in order to avoid tag collision if the two builds end up in the same docker repo.

**Comment by vrutkovs** [comment]
The tags would get overwritten, they won't collide

**Comment by lcarva** [comment]
The 4-digit string produced is not random:
```
 scratch-63379-20170531181947                 | running                 |                            
 scratch-63379-20170531182008                 | running                 |                            
 scratch-63379-20170531182009                 | running                 |
```

**Comment by vrutkovs** [comment]
Probably RNG was not seeded, as it returns the same value for any build
