### ISSUE TITLE
throw exception when in used config is specified both build_imagestream and build_image

### ISSUE THREAD

**Issue by rcerven** [projectatomic/osbs-client#508]
that way you will be sure which of them it is using

**Comment by vrutkovs** [comment]
This is very useful for debugging, both locally and on the builder.

@twaugh, @lcarva does this seem fair to you?

**Comment by twaugh** [comment]
Long term we'll want to require a new `buildroot_source` config item that specifies which is in use, or which takes some sort of URI which encodes whether to use a koji tag, an imagestream, or an image.

Until that happens, I'd be happy with an exception when both build_imagestream and build_image are specified.

**Comment by jarodwilson** [comment]
For improved user-friendliness, might be worth spitting out what we're getting as the defined build_image and build_imagestream values, i.e.:

+        if build_image and build_imagestream:
+            raise OsbsValidationException(
+                    'build_image=%s, build_imagestream=%s. Please only '
+                    'define build_image -OR- build_imagestream, not both'
+                    % (build_image, build_imagestream))
