### ISSUE TITLE
add tests for OSBS class

### ISSUE THREAD

**Issue by TomasTomecek** [projectatomic/osbs-client#52]

**Comment by twaugh** [comment]
First test written in 9b0cc19.

**Comment by TomasTomecek** [comment]
:+1:

**Comment by twaugh** [comment]
Still missing:
 * `create_prod_build()`
 * `create_prod_without_koji_build()`
 * `create_simple_build()`
 * `create_build()`
 * `create_build_from_buildrequest()`
 * `wait_for_build_to_finish()`

**Comment by vrutkovs** [comment]
Tests status:

 * [x] create_prod_build()
 * [x] create_prod_without_koji_build()
 * [x] create_simple_build()
 * [x] create_build() 
   (in `test_create_build_with_deprecated_params` and `test_create_prod_build_missing_args`)

 * [ ] create_build_from_buildrequest()
 * [x] wait_for_build_to_finish()

**Comment by lcarva** [comment]
Coverage has been improved.
