### ISSUE TITLE
Don't pad username with underscore

### ISSUE THREAD

**Issue by twaugh** [projectatomic/osbs-client#552]
Commit 9a4b478ae8a6d6650f1a1c790359bbb7c6e8a6cc introduced padding of the username with "_" to make it at least 4 characters. I don't remember what this is for, and it causes problems: https://github.com/projectatomic/atomic-reactor/issues/681.

@TomasTomecek, any chance you remember what this was originally for?

**Comment by twaugh** [comment]
See also https://github.com/projectatomic/atomic-reactor/issues/682.

**Comment by TomasTomecek** [comment]
@twaugh Back in days, docker required the names to be at least 4 letters. Seems like the regex for validation is changing with every version.

**Comment by lcarva** [comment]
Yeah, just came across this:
> A repository name is broken up into path components. A component of a repository name must be at least one lowercase, alpha-numeric characters, optionally separated by periods, dashes or underscores. More strictly, it must match the regular expression [a-z0-9]+(?:[._-][a-z0-9]+)*.

Maybe for v1 content, it still requires 4 characters? 

For fixing this issue, how about simply changing the padding character? Maybe just use `'x'`?
That way we can be sure we don't accidentally break backwards compatibility with v1 content.

**Comment by TomasTomecek** [comment]
Huh, looks like that it was docker <1.8 since short names work on 1.9:

```
$ docker tag fedora:25 x/x:latest
$ docker images x/x
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
x/x                 latest              23e53d43ea14        4 months ago        197.1 MB
$ docker version
Client:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-5.git64eb95e.fc22.x86_64
 Go version:      go1.5.3
 Git commit:      64eb95e/1.9.1
 Built:
 OS/Arch:         linux/amd64

Server:
 Version:         1.9.1
 API version:     1.21
 Package version: docker-1.9.1-5.git64eb95e.fc22.x86_64
 Go version:      go1.5.3
 Git commit:      64eb95e/1.9.1
 Built:
 OS/Arch:         linux/amd64
```

**Comment by lcarva** [comment]
This needs further testing in a full OSBS environment to determine the minimum amount of characters.

**Comment by TomasTomecek** [comment]
it would be awesome to see the regex for recent versions so guys know what to expect on a selected docker version
