### ISSUE TITLE
docs reference 'oc' without noting it means origin-clients

### ISSUE THREAD

**Issue by mlangsdorf** [projectatomic/osbs-client#569]
docs/backups.md refers to a command 'oc'. Naive users are going to assume that is a variant of osbs-client but it's actually in the origin-clients package. origin-clients is not mentioned in the documentation or requirements so this is not an intuitive package to install.

**Comment by vrutkovs** [comment]
Good catch! Its in `origin-clients` in Fedora or `openshift-clients` in RHEL, also available as a binary for other OSes
