### ISSUE TITLE
osbs.conf handling for node_selector.* keyword

### ISSUE THREAD

**Issue by mlangsdorf** [projectatomic/osbs-client#578]
When parsing cluster instance configs, keywords beginning "node_selector." should be interpreted as node_selector.platform and the value is a string or "none" for no value.

**Comment by twaugh** [comment]
Re-opening for BuildConfig modification required.

**Comment by twaugh** [comment]
This was fixed by:

- https://github.com/projectatomic/osbs-client/pull/586
- https://github.com/projectatomic/osbs-client/pull/611
- https://github.com/projectatomic/osbs-client/pull/612
