### ISSUE TITLE
Don't package customization files?

### ISSUE THREAD

**Issue by lcarva** [projectatomic/osbs-client#648]
I've noticed that all the `*_customize.json` files are being packaged. This means installing/uninstalling osbs-client (either via yum or pip) causes the customization files to be modified.

Do we want this behavior? I was under the impression that these files behaved similarly to a configuration file.

**Comment by lcarva** [comment]
cc @maxamillion

**Comment by twaugh** [comment]
We should not package them.

**Comment by maxamillion** [comment]
I think they should be packaged but marked as `%config(noreplace)`, this way a `rpm -qf` on the files provides the expected output.

**Comment by lcarva** [comment]
I think that makes sense for RPMs.

What about `setup.py`? Maybe it should be excluded from there as I don't think there's an equivalent in `setuptools.setup`.

**Comment by maxamillion** [comment]
@lcarva That makes sense, yes .... or if you'd like to just not include them at all in either place for the sake of uniformity, then they could be marked as `%ghost %config(noreplace)` for the RPMs.

**Comment by twaugh** [comment]
I think not packaging them and instead listing them as `%ghost %config(noreplace)` makes the most sense.
