### ISSUE TITLE
Various security related options are not configurable in json inputs

### ISSUE THREAD

**Issue by maxamillion** [projectatomic/osbs-client#658]
Currently there are various json files in [inputs](https://github.com/projectatomic/osbs-client/tree/master/inputs) that are used as templates but the security options (such as `"insecure": true`, `"verify_ssl": false`, and `"parent_registry_insecure": true`) are hard coded instead of configurable. This is insecure and it should be able to be configured.

**Comment by twaugh** [comment]
One option is to use plugin customization to override this, although it means overriding all the parameters at once.

**Comment by twaugh** [comment]
See also https://github.com/projectatomic/atomic-reactor/issues/687 -- common config across plugins. Seems related.

**Comment by maxamillion** [comment]
Sounds good! 👍

**Comment by twaugh** [comment]
We now have common config which encapsulates these options.
