### ISSUE TITLE
registry_uris is not forwarded to worker builds

### ISSUE THREAD

**Issue by lcarva** [projectatomic/osbs-client#756]
In `build_request.BuildRequest.render_orchestrate_build`, the value of `registry_uris` is not added to `config_kwargs`.

The workaround is to redefine `registry_uris` for each worker section in `osbs.conf` stored in  Secret object referenced by `client_config_secret`.

This is affects arrangement version <= 5. In arrangement version 6, this value is properly passed along to worker clusters via reactor config map.

**Comment by twaugh** [comment]
We've decided not to fix this and instead focus on removing support for arrangement versions < 6.
