### ISSUE TITLE
document how this fits into the "big picture" overall

### ISSUE THREAD

**Issue by ktdreyer** [projectatomic/osbs-client#831]
Hi folks, would you mind explaining how osbs-client in particular fits into the overall Koji + OSBS system?

Are OSBS users (container developers) ever intended to run osbs-client directly? What are the use-cases? Does fedpkg wrap osbs-client? Or maybe users are not supposed to install or use osbs-client at all?

It looks like https://github.com/release-engineering/koji-containerbuild uses the OSBS client in the kojid plugin code. So kojid uses osbs-client to interact with the OpenShift cluster? Is there any other use for osbs-client?

Background: I want to be able to parse the metadata.json files that OSBS generates as part of the content generator. I was looking for a library to do this, and I wondered if osbs-client would be that library.

**Comment by ktdreyer** [comment]
The readme says "All of this can be done from command line and from python"... it would be really helpful to give like a 10 line snippet of how someone would use this library, like at the complexity level of "hello world", or https://github.com/DBuildService/dockerfile-parse/#usage

**Comment by ktdreyer** [comment]
(see also https://github.com/release-engineering/koji-containerbuild/pull/105)

**Comment by twaugh** [comment]
Does http://osbs.readthedocs.io/ help? Users are not really expected to run osbs-client themselves at the moment because OSBS requires privileges on an OpenShift cluster.

**Comment by ktdreyer** [comment]
When you say "at the moment", does that mean there are future plans to have developers run `osbs-client` directly?

It would be great to edit the `README` here to clarify which software would ever run osbs-client. I think that would be:
1) koji-containerbuild
2) OSBS's orchestrator
3) anything else?

**Comment by twaugh** [comment]
That's right, only koji-containerbuild and the OSBS orchestrator builds are expected to run osbs-client directly. There are no future plans for developers to run osbs-client directly themselves.

**Comment by twaugh** [comment]
See what you think about #840.
