### ISSUE TITLE
Allow set Name, Version, Release via API

### ISSUE THREAD

**Issue by pbabinca** [projectatomic/osbs-client#89]
`add_dockerfile` plugin requires Name, Version, Release labels to be set unless nvr is provided. There doesn't seem to be possible to set nvr via osbs CLI nor the API.

**Comment by TomasTomecek** [comment]
We expect maintainers to set `N-V-R` labels in dockerfiles. Let's treat this as low-prio RFE (for development/debugging).

**Comment by lcarva** [comment]
This can get tricky in cases where Dockerfile also provides those values. We have not had the need for this since this issue was opened. Closing it.
